# Generated by Django 3.2.4 on 2021-12-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
    ]
