# Generated by Django 3.2.4 on 2021-12-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_register_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
